apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: buzb0t5zw-nodejs 
  janus-idp.io/tekton: buzb0t5zw-nodejs
  backstage.io/kubernetes-id: buzb0t5zw-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: buzb0t5zw-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml