apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: buzb0t5zw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: buzb0t5zw-nodejs 
  name: buzb0t5zw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: buzb0t5zw-nodejs 
